FROM rustlang/rust:nightly as my-custom-builder
RUN apt-get update
RUN echo "Some build-time system dependencies can be installed here."

{{generate_build_stages_with "my-custom-builder"}}

{{#binaries}}
FROM debian:stable-slim as my-awesome-binaries
RUN echo "Can setup binaries image here."
{{/binaries}}

{{#tests}}
FROM debian:stable-slim as my-awesome-tests
RUN echo "Can setup tests image here: copy static fixtures or install dependencies."
{{/tests}}